stays/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    # /home
    path("", views.home, name="home"),
    path(
        "publications/publication/<uuid:publication_uuid>/picture",
        views.serve_publication_picture,
        name="serve_publication_picture",
    ),
    path(
        "publications/publication/<uuid:publication_uuid>/audio",
        views.serve_publication_audio,
        name="serve_publication_audio",
    ),
    path(
        "publications/publication/rm",
        views.PublicationDeleteView.as_view(),
        name="delete_publication",
    ),
    path(
        "publications/publication/<uuid:uuid>",
        views.PublicationDetailView.as_view(),
        name="publication",
    ),
    path(
        "publications/publication/<uuid:pk>/edit",
        views.PublicationUpdateView.as_view(),
        name="edit_publication",
    ),
    path(
        "publications/publication/<uuid:uuid>/upvote",
        views.toggle_upvote,
        name="upvote",
    ),
    path(
        "publications/publication/<uuid:uuid>/check_user_upvoted",
        views.check_user_upvoted_publication,
        name="check_user_upvoted",
    ),
    path("contact", views.ContactAdminView.as_view(), name="contact"),
]

stays/stays/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from stays.api import api
from stays.utils.errors_helpers import random_error_handler

# from machina import urls as machina_urls


urlpatterns = [
    path("admin", admin.site.urls),
    path("admin/defender/", include("defender.urls")),
    path("", include("core.urls")),
    path("", include("locations.urls")),
    path("", include("users.urls")),
    path("api/", api.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = "stays.urls.handler400"
handler401 = "stays.urls.handler401"
handler403 = "stays.urls.handler403"
handler404 = "stays.urls.handler404"
handler410 = "stays.urls.handler410"
handler418 = "stays.urls.handler418"
handler429 = "stays.urls.handler429"
handler500 = "stays.urls.handler500"
handler503 = "stays.urls.handler503"
handler504 = "stays.urls.handler504"


# Error handlers WHEN DEBUG=TRUE
def handler400(request, exception):
    return random_error_handler(request, 400)


def handler401(request, exception):
    return random_error_handler(request, 401)


def handler403(request, exception):
    return random_error_handler(request, 403)


def handler404(request, exception):
    return random_error_handler(request, 404)


def handler410(request, exception):
    return random_error_handler(request, 410)


def handler418(request, exception):
    return random_error_handler(request, 418)


def handler429(request, exception):
    return random_error_handler(request, 429)


def handler500(request):
    return random_error_handler(request, 500)


def handler503(request, exception):
    return random_error_handler(request, 503)


def handler504(request, exception):
    return random_error_handler(request, 504)


def handlerOther(request, exception=None):
    # 520 is an example. You can use any HTTP status code that you want to handle.
    return random_error_handler(request, 520)

stays/users/urls.py
from django.contrib.auth import views as authentication_views
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("signup", views.CreateProfileView.as_view(), name="signup"),
    path(
        "login",
        views.AccountLoginView.as_view(template_name="signin.html"),
        name="login",
    ),
    path(
        "logout",
        authentication_views.LogoutView.as_view(template_name="signout.html"),
        name="logout",
    ),
    path("password/reset", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password/reset/done",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password/reset/<uidb64>/<token>",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/complete",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("account/<slug:slug>", views.AccountDetailsView.as_view(), name="account"),
    path(
        "account/<slug:slug>/stays", views.ProfileStaysListView.as_view(), name="stays"
    ),
    path("account/<slug:slug>/publish", views.PublishView.as_view(), name="publish"),
    path(
        "account/<slug:slug>/settings",
        views.UpdateAccountView.as_view(),
        name="settings",
    ),
    path(
        "account/<slug:slug>/delete",
        views.DeleteProfileView.as_view(),
        name="delete_account",
    ),
    # path("", include('allauth.urls')),
    path(
        "profile/<slug:slug>/public", views.ProfileDetailView.as_view(), name="profile"
    ),
    path(
        "profile/<slug:slug>/followtoggle", views.follow_profile, name="follow_unfollow"
    ),
    path(
        "profile/<slug:slug>/following",
        views.FollowingListView.as_view(),
        name="following",
    ),
    path(
        "profile/<slug:slug>/followers",
        views.FollowersListView.as_view(),
        name="followers",
    ),
]

stays/templates/418-a.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<main class="vh-100 d-flex justify-content-center align-items-center">
    <div class="text-center">
        <img src="{% static 'assets/images/http-status/418-im-a-teapot.png' %}" alt="" class="img-fluid" style="max-width: 100%; height: auto;">
    </div>
</main>
{% endblock content %}

stays/templates/504-a.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<main class="vh-100 d-flex justify-content-center align-items-center">
    <div class="text-center">
        <img src="{% static 'assets/images/http-status/504-gateway-timeout.png' %}" alt="" class="img-fluid" style="max-width: 100%; height: auto;">
    </div>
</main>
{% endblock content %}

stays/templates/account.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Account
{% endblock title %}
<main>
    {% block content %}
    <div class="container d-flex justify-content-center">
        <div class="card w-100">
            <div class="card-body text-center">
                <h1 class="card-title">
                    <a href="{% url 'users:profile' current_user.slug %}" class="text-dark">
                        {% if current_user.username is not None and current_user.username != "" %}
                        <b>Welcome, {{ current_user.username }}</b>
                        {% else %}
                        <b>< {{ current_user.email }} - Please define a username ></b>
                        {% endif %}
                    </a>
                </h1>
                <hr>
                <div class="btn-group mb-3 w-75 mx-auto" role="group" aria-label="Basic example">
                    <a href="{% url 'core:home' %}" class="btn btn-primary">Home</a>
                    {% if number_of_publications %}
                        <a href="{% url 'users:stays' current_user.slug %}" class="btn btn-secondary btn-light ">Your Stays</a>
                    {% endif %}
                    <a href="{% url 'users:publish' current_user.slug %}" class="btn btn-success">Publish</a>
                    <a href="{% url 'users:settings' current_user.slug %}" class="btn btn-info">Settings</a>
                </div>
                <div class="btn-group mb-3 w-75 mx-auto" role="group" aria-label="Basic example">
                    {% if profile_has_followers %}
                    <a href="{% url 'users:followers' current_user.slug %}" class="btn btn-danger">Your followers</a>
                    {% endif %}
                    {% if profile_follows_stayers %}
                    <a href="{% url 'users:following' current_user.slug %}" class="btn btn-warning">Favourite Stayers</a>
                    {% endif %}
                </div>
                {% if profile.profile_picture and profile.profile_picture != "None" %}
                    <!-- Image -->
                    <div class="d-flex justify-content-center">
                        <a href="#" data-bs-toggle="modal" data-bs-target="#profilePictureModal">
                            <img src="{{ profile.profile_picture.url }}" class="rounded-circle img-fluid mb-3" style="max-width: 50%;">
                        </a>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="profilePictureModal" tabindex="-1" aria-labelledby="profilePictureModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <img src="{{ profile.profile_picture.url }}" class="img-fluid">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <h3 class="card-subtitle mb-2 text-muted">Short story long</h3>
                {% if number_of_following %}
                <h5>{{ profile.username }} follows {{ number_of_following }} Stayer(s).</h5>
                {% endif %}
                {% if number_of_followers %}
                <h5>{{ number_of_followers }} Stayer(s) are following {{ profile.username }} </h5>
                {% endif %}
                <a href="{% url 'users:settings' current_user.slug %}"><h6>Edit Profile</h6></a>

                <div class="container d-flex justify-content-center ">
                    <div class="accordion col-md-8" id="userInformationAccordion">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingEmail">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEmail" aria-expanded="false" aria-controls="collapseEmail">
                                    Email
                                </button>
                            </h2>
                            <div id="collapseEmail" class="accordion-collapse collapse" aria-labelledby="headingEmail" data-bs-parent="#userInformationAccordion">
                                <div class="accordion-body">
                                    {{ current_user.email }}
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingUsername">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseUsername" aria-expanded="false" aria-controls="collapseUsername">
                                    Username
                                </button>
                            </h2>
                            <div id="collapseUsername" class="accordion-collapse collapse" aria-labelledby="headingUsername" data-bs-parent="#userInformationAccordion">
                                <div class="accordion-body">
                                    {{ current_user.username }}
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingCreatedAt">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCreatedAt" aria-expanded="false" aria-controls="collapseCreatedAt">
                                    Created At
                                </button>
                            </h2>
                            <div id="collapseCreatedAt" class="accordion-collapse collapse" aria-labelledby="headingCreatedAt" data-bs-parent="#userInformationAccordion">
                                <div class="accordion-body">
                                    {{ current_user.created_at }}
                                </div>
                            </div>
                        </div>
                        {% if current_user.about_text %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingAbout">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAbout" aria-expanded="false" aria-controls="collapseAbout">
                                    About
                                </button>
                            </h2>
                            <div id="collapseAbout" class="accordion-collapse collapse" aria-labelledby="headingAbout" data-bs-parent="#userInformationAccordion">
                                <div class="accordion-body">
                                    {{ current_user.about_text }}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if current_user.season_of_birth or current_user.year_of_birth or continent_of_birth %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingBirth">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseBirth" aria-expanded="false" aria-controls="collapseBirth">
                                    Birth
                                </button>
                            </h2>
                            <div id="collapseBirth" class="accordion-collapse collapse" aria-labelledby="headingBirth" data-bs-parent="#userInformationAccordion">
                                <div class="accordion-body">
                                    {% if current_user.season_of_birth %}
                                    {{ current_user.season_of_birth }}
                                    {% endif %}
                                    {% if current_user.year_of_birth %}
                                        , {{ current_user.year_of_birth }}
                                    {% endif %}
                                    {% if continent_of_birth %}
                                        , {{ continent_of_birth }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if current_user.motto %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingMotto">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseMotto" aria-expanded="false" aria-controls="collapseMotto">
                                    Motto
                                </button>
                            </h2>
                            <div id="collapseMotto" class="accordion-collapse collapse" aria-labelledby="headingMotto" data-bs-parent="#userInformationAccordion">
                                <div class="accordion-body">
                                    « {{ current_user.motto }} »
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if current_user.signature %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingSignature">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSignature" aria-expanded="false" aria-controls="collapseSignature">
                                    Signature
                                </button>
                            </h2>
                            <div id="collapseSignature" class="accordion-collapse collapse" aria-labelledby="headingSignature" data-bs-parent="#userInformationAccordion">
                                <div class="accordion-body">
                                    « {{ current_user.signature }} »
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endblock content %}
</main>
    

stays/templates/contact.html
{% extends "base.html" %}
{% load static %}

<style>
    body {
        background-image: url({% static 'assets/images/logo.png' %});
        background-size: cover;
        background-position: center;
    }
</style>

<main>
    {% block content %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger d-flex align-items-center d-flex justify-content-around" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                {{ message }}
            </div>
        </div>
        {% endfor %}
    {% endif %}
    <div class="container d-flex align-items-center justify-content-center" style="height: calc(100vh - (header height + footer height))">
        <form method="post" class="row g-3 bg-white rounded border border-primary col-12 col-lg-8 mx-auto p-4" style="max-width: 72%;">
            {% csrf_token %}
            <div class="col-12">
                <label for="subject" class="form-label text-black">Subject</label>
                <input type="text" class="form-control" name="subject" id="subject" placeholder="" style="color: black;">
            </div>
            <div class="col-12">
                <label for="name" class="form-label text-black">Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Enter your name" style="color: black;">
            </div>
            <div class="col-12">
                <label for="email" class="form-label text-black">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" style="color: black;">
            </div>
            <div class="col-12">
                <label for="message" class="form-label text-black">Message</label>
                <textarea class="form-control" id="message" name="message" rows="3" placeholder="Enter your message" style="color: black;"></textarea>
            </div>
            <div class="col-12 d-flex justify-content-center">
                <button type="submit" class="btn btn-warning btn-block col-12 col-md-6">Send</button>
            </div>
        </form>
    </div>
    {% endblock content %}
</main>

stays/templates/delete_post.html
{% extends "base.html" %}
{% load static %}



<main>
    {% block content %}
    
    {% endblock content %}
</main>

stays/templates/followers.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Followers
{% endblock title %}
<main>
    {% block content %}
    <div class="container">
        <div class="row justify-content-center">
            {% for follower in followers %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 text-center text-dark mb-4">
                <div class="p-3 border bg-light">
                    <a href="{% url 'users:profile' follower.slug %}">
                        {{ follower.username }}
                    </a>
                </div>
            </div>
            {% empty %}
            <p>No followers yet.</p>
            {% endfor %}
        </div>
    </div>
    {% endblock content %}
</main>

stays/templates/header.html
<header>
    <div class="header_inner">
        <div class="left-side">
            <!-- Logo -->
            <div id="logo" class="uk-hidden@s">
                <a href="{% url 'core:home' %}">
                    <b><h1 style="text-transform: uppercase;">STAYS : Remember them. Share them. Warm hearts.</h1></b>
                </a>
            </div>
  
            <div class="header_search">
                <input type="text" class="form-control" placeholder="Search for username..">
                <div class="icon-search">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                    </svg>
                </div>
            </div>
        </div>
  
        <div class="right-side lg:pr-4">
            <!-- Upload -->
            {% if user.is_authenticated %}
            <a href="{% url 'users:publish' user.slug %}"
                class="bg-pink-500 flex font-bold hidden hover:bg-pink-600 hover:text-white inline-block items-center lg:block max-h-10 mr-4 px-4 py-2 rounded shado text-white">
                <ion-icon name="add-circle" class="-mb-1 mr-1 opacity-90 text-xl uilus-circle"></ion-icon>
                Share an experience
            </a>
            {% endif %}
  
            <!-- Notification -->
            {% if user.is_authenticated %}
            <a href="#" class="header-links-item">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" width="1em" height="1em"
                    role="img">
                    <g fill="none">
                        <path
                            d="M12 22a2.02 2.02 0 0 1-2.01-2h4a2.02 2.02 0 0 1-.15.78a2.042 2.042 0 0 1-1.44 1.18h-.047A1.922 1.922 0 0 1 12 22zm8-3H4v-2l2-1v-5.5a8.065 8.065 0 0 1 .924-4.06A4.654 4.654 0 0 1 10 4.18V2h4v2.18c2.579.614 4 2.858 4 6.32V16l2 1v2z"
                            fill="currentColor" />
                    </g>
                </svg>
            </a>
            {% endif %}
            <!-- ... (Rest of the code) ... -->
  
            <!-- Profile -->
            <a href="#">
                {% if user.is_authenticated %}
                    <img src="{{ user.profile_picture }}" class="header-avatar" alt="">
                {% else %}
                    <img src="{% static 'assets/images/avatars/icons8-login-64.png' %}" class="header-avatar"
                        alt="https://icons8.com/icon/Hm0e3BaO54rH/login">
                {% endif %}
            </a>
            <div uk-drop="mode: click;offset:9"
                class="header_dropdown profile_dropdown border-t">
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'users:account' user.slug %}">Account</a></li>
                        <li><a href="{% url 'users:logout' %}">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}">Sign In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</header>

stays/templates/password_reset_form.html
{% extends "base.html" %}
{% load static %}



<link href="{% static 'css/reset_password.css' %}" rel="stylesheet">
<main>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }
        .form-container {
            background-color: #ffffff !important;
            padding: 20px !important;
            border-radius: 8px !important;
            box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1) !important;
            width: 300px !important;
        }
        
        .form-container button {
            background-color: #007bff !important;
            color: #ffffff !important;
            border: none !important;
            padding: 10px 20px !important;
            text-align: center !important;
            text-decoration: none !important;
            display: inline-block !important;
            font-size: 16px !important;
            margin: 10px 2px !important;
            cursor: pointer !important;
            border-radius: 4px !important;
        }
    </style>
    {% block content %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger d-flex align-items-center d-flex justify-content-around" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                {{ message }}
            </div>
        </div>
        {% endfor %}
    {% endif %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <form method="post" action="{% url 'users:password_reset' %}" > 
                    {% csrf_token %}
                    <div class="mb-3">
                        <center><label for="exampleInputEmail1" class="form-label">{{ form.email.label }}</label></center>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="{{ form.email.name }}">
                    </div>
                    <center><button type="submit" class="btn btn-primary">Reset password</button></center>
                </form>
            </div>
        </div>
    </div>
    {% endblock content %}
</main>

stays/templates/stays.html
{% extends "base.html" %}
{% load static %}
{% comment %} {% load cool_paginate %} {% endcomment %}
{% load pagination_tags %}
{% block title %}
STAYS
{% endblock title %}

<main>
    {% block content %}
    <style>
        body {
            background-color: black !important;
        }
        .card:hover .card-img {
            /*transform: scale(1.6);*/
            opacity: 0.1;
        }
        .card:hover {
            transform: scale(1.1);
        }
        .card .card-img {
            transition: opacity 0.3s ease;
        }
        .card .card-img-overlay {
            opacity: 0;
            transition: opacity 0.2s ease;
            {% comment %} overflow: auto; {% endcomment %}
        }
        .card:hover .card-img-overlay {
            opacity: 1;
        }
        .card .card-img-overlay div {
            text-align: center;
        }

        .card p {
            margin: 0.05em 0; /* Réduit l'espace entre les éléments <p> */
        }
        .card h3 {
            margin: 0.05em 0; /* Réduit l'espace entre les éléments <p> */
        }
        .w-80 {
            width: 84% !important;
        }
        .site-content {
            width: 100%; !important;
        }
        container {
            margin-right: inherit !important;
        }
        .row.row-cols-1.row-cols-md-3.g-2 {
            display: flex !important;
            flex-wrap: wrap !important;
            align-items: flex-start !important;
        }
    </style>
    <div class="container w-100">
        {% if publications.author_username != "None" %}
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body text-center">
                        <a href="{% url 'users:profile' publications.author_slug %}"><h2 class="text-dark">Stays of {{ publications.author_username }}</h2></a>
                    </div>
                </div>
            </div>
        </div>
        <br>
        {% endif %}
        {% if publications.author_motto != "None" %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="text-dark">{{ publications.author_motto }}</h2>
                    </div>
                </div>
            </div>
        </div>
        <br>
        {% endif %}
        <div class="row row-cols-sm-1 row-cols-md-2  row-cols-lg-3 row-cols-xl-4 g-2 mx-auto w-100 justify-content-center align-item-center" style="width: 85%;">
            {% autopaginate page_obj 9 %}
            {% for publication in page_obj %}
            <div class="col">
                <div class="card bg-dark text-white border-1">
                    <img loading="lazy" src="{{ publication.picture.url }}" class="card-img" alt="{{ publication.title }}">
                    <div class="card-img-overlay d-flex align-items-center justify-content-center">
                        <div>
                            <a href="{% url 'core:publication' publication.uuid %}" class="text-decoration-none text-reset">
                                <h3 class="card-title"> {{ publication.title }} </h3>
                                <p class="card-text">{{ publication.stay_country_name }}, {{ publication.stay_continent_code }}</p>
                                <p class="card-text">{{ publication.year_of_stay }}, {{ publication.season_of_stay }}</p>
                                <p class="card-text">Published {{ publication.created_at }}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="d-flex justify-content-center mt-6">
        <div class="d-flex justify-content-center mt-6">
            {% comment %} {% block paginator %} {% endcomment %}
            {% comment %} <h1>{{ page_obj }}</h1> {% endcomment %}
            {% comment %} {% cool_paginate %} {% endcomment %}
            {% comment %} {% cool_paginate page_obj=publications %} {% endcomment %}
            {% comment %} {% cool_paginate page_obj=publication %} {% endcomment %}
            {% comment %} {% endblock paginator %} {% endcomment %}
        </div>
    </div>
    {% endblock content %}
</main>
{% block scripts %}
    {{ block.super }}
    <script src="https://unpkg.com/packery@2/dist/packery.pkgd.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            var grid = document.querySelector('.row.row-cols-1.row-cols-md-3.g-2');
            var images = grid.querySelectorAll('img');
            var imagesLoaded = 0;

            images.forEach((img) => {
                img.addEventListener('load', () => {
                    imagesLoaded++;
                    if (imagesLoaded === images.length) {
                        var pckry = new Packery(grid, {
                            // options
                            itemSelector: '.col',
                            gutter: 3,
                            columnWidth: '.col'
                        });
                    }
                });
            });
        });
    </script>
{% endblock scripts %}